name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up vcpkg
        shell: pwsh
        run: |
          cd vcpkg
          /bootstrap-vcpkg.bat
          cd ..
          vcpkg/vcpkg.exe add port opencv4

      - name: Set up mediapipe
        shell: pwsh
        run: |
          cd src/mediapipe
          curl -o hand_landmarker.task https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task
          cd ../..
    
      - name: Configure CMake
        shell: pwsh
        run: >
          cmake -B %BUILD_DIR% -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
    
      - name: Build
        shell: pwsh
        run: cmake --build build --config Debug

  build-macos-arm:
    name: macOS ARM64
    runs-on: macos-15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install OpenCV
        run: brew install opencv

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DOpenCV_DIR="$(brew --prefix opencv)/lib/cmake/opencv4"

      - name: Build
        run: cmake --build build --config Debug
