name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    env:
      # Tell vcpkg to store compiled package archives in a folder inside the workspace.
      # We then cache that folder between workflow runs.
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\.vcpkg-cache

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore vcpkg cache
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ runner.os }}-x64-windows-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-x64-windows-

      - name: Set up vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg ./vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.bat
          cd ..
          vcpkg/vcpkg.exe add port opencv4

      - name: Configure CMake
        shell: pwsh
        run: >
          cmake -B %BUILD_DIR% -DCMAKE_TOOLCHAIN_FILE={{ github.workspace }}vcpkg/scripts/buildsystems/vcpkg.cmake
    
      #- name: Build
      #  shell: pwsh
      #  run: cmake --build build --config Debug

  build-macos-arm:
    name: MacOS
    runs-on: macos-15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install OpenCV
        run: brew install opencv

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DOpenCV_DIR="$(brew --prefix opencv)/lib/cmake/opencv4"

      - name: Build
        run: cmake --build build --config Debug
